import type {
  AiLogAnalysis,
  CloudWatchAlarm,
  CostData,
  DeployConfig,
  EC2Instance,
  ECSCluster,
  ECSEvent,
  ECSService,
  ECSTask,
  IAMUser,
  JenkinsBuild,
  JenkinsJob,
  JenkinsQueueItem,
  JenkinsServerInfo,
  LambdaFunction,
  LogEntry,
  LogGroup,
  MetricDataPoint,
  S3Bucket,
  VPC,
  WafRule,
  WafTopThreat,
  WafTrafficData,
  WafWebAcl,
} from "@shared/types";

export const ec2Instances: EC2Instance[] = [
  {
    id: "i-0a1b2c3d4e5f6g7h8",
    name: "prod-web-01",
    type: "t3.large",
    state: "running",
    az: "us-east-1a",
    publicIp: "54.210.123.45",
    privateIp: "10.0.1.15",
    cpu: 34,
    memory: 62,
    launchTime: "2026-01-15T08:30:00Z",
  },
  {
    id: "i-1b2c3d4e5f6g7h8i9",
    name: "prod-web-02",
    type: "t3.large",
    state: "running",
    az: "us-east-1b",
    publicIp: "54.210.123.46",
    privateIp: "10.0.2.15",
    cpu: 28,
    memory: 55,
    launchTime: "2026-01-15T08:31:00Z",
  },
  {
    id: "i-2c3d4e5f6g7h8i9j0",
    name: "prod-api-01",
    type: "m5.xlarge",
    state: "running",
    az: "us-east-1a",
    publicIp: "54.210.124.10",
    privateIp: "10.0.1.20",
    cpu: 67,
    memory: 78,
    launchTime: "2026-02-01T12:00:00Z",
  },
  {
    id: "i-3d4e5f6g7h8i9j0k1",
    name: "staging-web-01",
    type: "t3.medium",
    state: "running",
    az: "us-east-1a",
    publicIp: "54.210.125.20",
    privateIp: "10.0.3.10",
    cpu: 12,
    memory: 35,
    launchTime: "2026-02-10T09:00:00Z",
  },
  {
    id: "i-4e5f6g7h8i9j0k1l2",
    name: "dev-worker-01",
    type: "t3.small",
    state: "stopped",
    az: "us-east-1b",
    publicIp: "-",
    privateIp: "10.0.4.5",
    cpu: 0,
    memory: 0,
    launchTime: "2026-01-20T14:00:00Z",
  },
  {
    id: "i-5f6g7h8i9j0k1l2m3",
    name: "bastion-host",
    type: "t3.micro",
    state: "running",
    az: "us-east-1a",
    publicIp: "54.210.126.30",
    privateIp: "10.0.0.10",
    cpu: 5,
    memory: 18,
    launchTime: "2025-12-01T06:00:00Z",
  },
];

export const s3Buckets: S3Bucket[] = [
  {
    name: "prod-assets-cdn",
    region: "us-east-1",
    sizeGb: 245.8,
    objects: 128430,
    access: "public-read",
    versioning: true,
    createdAt: "2025-06-15",
  },
  {
    name: "prod-backups",
    region: "us-east-1",
    sizeGb: 1024.5,
    objects: 3521,
    access: "private",
    versioning: true,
    createdAt: "2025-03-20",
  },
  {
    name: "app-logs-archive",
    region: "us-east-1",
    sizeGb: 512.3,
    objects: 45890,
    access: "private",
    versioning: false,
    createdAt: "2025-07-10",
  },
  {
    name: "staging-uploads",
    region: "us-east-1",
    sizeGb: 18.7,
    objects: 2340,
    access: "authenticated-read",
    versioning: true,
    createdAt: "2025-09-01",
  },
  {
    name: "terraform-state",
    region: "us-east-1",
    sizeGb: 0.1,
    objects: 45,
    access: "private",
    versioning: true,
    createdAt: "2025-01-10",
  },
];

export const cloudWatchAlarms: CloudWatchAlarm[] = [
  {
    name: "prod-web-high-cpu",
    metric: "CPUUtilization",
    namespace: "AWS/EC2",
    state: "OK",
    threshold: "> 80%",
    period: "5 min",
  },
  {
    name: "prod-api-high-cpu",
    metric: "CPUUtilization",
    namespace: "AWS/EC2",
    state: "ALARM",
    threshold: "> 80%",
    period: "5 min",
  },
  {
    name: "rds-connections",
    metric: "DatabaseConnections",
    namespace: "AWS/RDS",
    state: "OK",
    threshold: "> 100",
    period: "5 min",
  },
  {
    name: "alb-5xx-errors",
    metric: "HTTPCode_Target_5XX",
    namespace: "AWS/ALB",
    state: "ALARM",
    threshold: "> 10",
    period: "1 min",
  },
  {
    name: "lambda-errors",
    metric: "Errors",
    namespace: "AWS/Lambda",
    state: "OK",
    threshold: "> 5",
    period: "5 min",
  },
  {
    name: "s3-bucket-size",
    metric: "BucketSizeBytes",
    namespace: "AWS/S3",
    state: "INSUFFICIENT_DATA",
    threshold: "> 1TB",
    period: "1 day",
  },
];

export const iamUsers: IAMUser[] = [
  {
    name: "admin-chris",
    arn: "arn:aws:iam::123456789012:user/admin-chris",
    groups: ["Administrators", "Billing"],
    mfaEnabled: true,
    lastActive: "2026-03-01T10:30:00Z",
    accessKeys: 1,
  },
  {
    name: "dev-sarah",
    arn: "arn:aws:iam::123456789012:user/dev-sarah",
    groups: ["Developers"],
    mfaEnabled: true,
    lastActive: "2026-02-28T16:45:00Z",
    accessKeys: 2,
  },
  {
    name: "ci-pipeline",
    arn: "arn:aws:iam::123456789012:user/ci-pipeline",
    groups: ["CI-CD"],
    mfaEnabled: false,
    lastActive: "2026-03-01T08:00:00Z",
    accessKeys: 1,
  },
  {
    name: "readonly-auditor",
    arn: "arn:aws:iam::123456789012:user/readonly-auditor",
    groups: ["ReadOnly", "SecurityAudit"],
    mfaEnabled: true,
    lastActive: "2026-02-25T11:00:00Z",
    accessKeys: 0,
  },
  {
    name: "ops-mike",
    arn: "arn:aws:iam::123456789012:user/ops-mike",
    groups: ["Operations", "Developers"],
    mfaEnabled: true,
    lastActive: "2026-03-01T09:15:00Z",
    accessKeys: 1,
  },
];

export const lambdaFunctions: LambdaFunction[] = [
  {
    name: "api-auth-handler",
    runtime: "nodejs20.x",
    memory: 256,
    timeout: 30,
    lastInvoked: "2026-03-01T10:45:00Z",
    invocations24h: 45230,
    errors24h: 12,
  },
  {
    name: "image-resize",
    runtime: "nodejs20.x",
    memory: 512,
    timeout: 60,
    lastInvoked: "2026-03-01T10:30:00Z",
    invocations24h: 8920,
    errors24h: 3,
  },
  {
    name: "cron-cleanup",
    runtime: "python3.12",
    memory: 128,
    timeout: 300,
    lastInvoked: "2026-03-01T06:00:00Z",
    invocations24h: 24,
    errors24h: 0,
  },
  {
    name: "webhook-processor",
    runtime: "nodejs20.x",
    memory: 256,
    timeout: 30,
    lastInvoked: "2026-03-01T10:44:00Z",
    invocations24h: 15340,
    errors24h: 45,
  },
];

export const vpcs: VPC[] = [
  {
    id: "vpc-0abc123def456",
    name: "production",
    cidr: "10.0.0.0/16",
    subnets: 6,
    region: "us-east-1",
    isDefault: false,
  },
  {
    id: "vpc-1def456ghi789",
    name: "staging",
    cidr: "10.1.0.0/16",
    subnets: 4,
    region: "us-east-1",
    isDefault: false,
  },
  {
    id: "vpc-2ghi789jkl012",
    name: "default",
    cidr: "172.31.0.0/16",
    subnets: 3,
    region: "us-east-1",
    isDefault: true,
  },
];

export const costHistory: CostData[] = [
  { month: "Sep", ec2: 2800, s3: 420, rds: 1200, lambda: 85, other: 650 },
  { month: "Oct", ec2: 2950, s3: 435, rds: 1200, lambda: 92, other: 680 },
  { month: "Nov", ec2: 3100, s3: 450, rds: 1200, lambda: 110, other: 710 },
  { month: "Dec", ec2: 2700, s3: 460, rds: 1200, lambda: 95, other: 690 },
  { month: "Jan", ec2: 3200, s3: 480, rds: 1350, lambda: 120, other: 730 },
  { month: "Feb", ec2: 3150, s3: 495, rds: 1350, lambda: 135, other: 750 },
];

export const cpuMetrics: MetricDataPoint[] = [
  { time: "00:00", value: 42 },
  { time: "01:00", value: 38 },
  { time: "02:00", value: 35 },
  { time: "03:00", value: 31 },
  { time: "04:00", value: 29 },
  { time: "05:00", value: 33 },
  { time: "06:00", value: 45 },
  { time: "07:00", value: 58 },
  { time: "08:00", value: 67 },
  { time: "09:00", value: 72 },
  { time: "10:00", value: 75 },
  { time: "11:00", value: 71 },
  { time: "12:00", value: 68 },
  { time: "13:00", value: 73 },
  { time: "14:00", value: 76 },
  { time: "15:00", value: 74 },
  { time: "16:00", value: 69 },
  { time: "17:00", value: 63 },
  { time: "18:00", value: 55 },
  { time: "19:00", value: 49 },
  { time: "20:00", value: 52 },
  { time: "21:00", value: 47 },
  { time: "22:00", value: 44 },
  { time: "23:00", value: 40 },
];

export const networkMetrics: MetricDataPoint[] = [
  { time: "00:00", value: 82 },
  { time: "01:00", value: 74 },
  { time: "02:00", value: 68 },
  { time: "03:00", value: 61 },
  { time: "04:00", value: 57 },
  { time: "05:00", value: 65 },
  { time: "06:00", value: 98 },
  { time: "07:00", value: 134 },
  { time: "08:00", value: 168 },
  { time: "09:00", value: 187 },
  { time: "10:00", value: 195 },
  { time: "11:00", value: 201 },
  { time: "12:00", value: 178 },
  { time: "13:00", value: 192 },
  { time: "14:00", value: 210 },
  { time: "15:00", value: 205 },
  { time: "16:00", value: 183 },
  { time: "17:00", value: 162 },
  { time: "18:00", value: 141 },
  { time: "19:00", value: 118 },
  { time: "20:00", value: 127 },
  { time: "21:00", value: 110 },
  { time: "22:00", value: 95 },
  { time: "23:00", value: 87 },
];

// ─── Log Explorer ─────────────────────────────────────────────────────────────

export const logGroups: LogGroup[] = [
  {
    name: "/aws/lambda/api-auth-handler",
    retentionDays: 30,
    storedBytes: 524288000,
    streamCount: 12,
    lastEvent: "2026-03-01T10:58:42.000Z",
  },
  {
    name: "/aws/lambda/image-resize",
    retentionDays: 14,
    storedBytes: 209715200,
    streamCount: 8,
    lastEvent: "2026-03-01T10:55:10.000Z",
  },
  {
    name: "/ecs/prod-web",
    retentionDays: 90,
    storedBytes: 2147483648,
    streamCount: 24,
    lastEvent: "2026-03-01T10:59:01.000Z",
  },
  {
    name: "/aws/apigateway/prod-api",
    retentionDays: 7,
    storedBytes: 104857600,
    streamCount: 4,
    lastEvent: "2026-03-01T10:57:33.000Z",
  },
  {
    name: "/aws/waf/prod-acl",
    retentionDays: 30,
    storedBytes: 314572800,
    streamCount: 2,
    lastEvent: "2026-03-01T10:58:55.000Z",
  },
];

export const logEntries: LogEntry[] = [
  {
    id: "log-001",
    timestamp: "2026-03-01T10:58:42.345Z",
    logGroup: "/aws/lambda/api-auth-handler",
    logStream: "2026/03/01/[$LATEST]a1b2c3d4e5f6",
    level: "ERROR",
    message: "Task timed out after 30.01 seconds",
    requestId: "f3a1b2c3-d4e5-f6a7-b8c9-d0e1f2a3b4c5",
    source: "api-auth-handler",
  },
  {
    id: "log-002",
    timestamp: "2026-03-01T10:57:18.112Z",
    logGroup: "/aws/lambda/api-auth-handler",
    logStream: "2026/03/01/[$LATEST]a1b2c3d4e5f6",
    level: "WARN",
    message: "Cold start detected — init duration 1234ms. Consider provisioned concurrency.",
    requestId: "a9b8c7d6-e5f4-a3b2-c1d0-e9f8a7b6c5d4",
    source: "api-auth-handler",
  },
  {
    id: "log-003",
    timestamp: "2026-03-01T10:56:05.889Z",
    logGroup: "/aws/lambda/api-auth-handler",
    logStream: "2026/03/01/[$LATEST]a1b2c3d4e5f6",
    level: "INFO",
    message: "START RequestId: c3d4e5f6-a7b8-c9d0-e1f2-a3b4c5d6e7f8 Version: $LATEST",
    requestId: "c3d4e5f6-a7b8-c9d0-e1f2-a3b4c5d6e7f8",
    source: "api-auth-handler",
  },
  {
    id: "log-004",
    timestamp: "2026-03-01T10:55:59.001Z",
    logGroup: "/aws/lambda/api-auth-handler",
    logStream: "2026/03/01/[$LATEST]a1b2c3d4e5f6",
    level: "FATAL",
    message:
      "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory. Memory limit 256 MB exceeded.",
    requestId: "d4e5f6a7-b8c9-d0e1-f2a3-b4c5d6e7f8a9",
    source: "api-auth-handler",
  },
  {
    id: "log-005",
    timestamp: "2026-03-01T10:54:22.774Z",
    logGroup: "/aws/lambda/image-resize",
    logStream: "2026/03/01/[$LATEST]b2c3d4e5f6a7",
    level: "INFO",
    message:
      "Image resize complete: input=s3://prod-assets-cdn/uploads/photo-4928.jpg output=s3://prod-assets-cdn/thumbnails/photo-4928_thumb.jpg duration=340ms",
    requestId: "e5f6a7b8-c9d0-e1f2-a3b4-c5d6e7f8a9b0",
    source: "image-resize",
  },
  {
    id: "log-006",
    timestamp: "2026-03-01T10:53:10.330Z",
    logGroup: "/aws/lambda/image-resize",
    logStream: "2026/03/01/[$LATEST]b2c3d4e5f6a7",
    level: "WARN",
    message:
      "Unsupported image format HEIC detected, falling back to ImageMagick conversion — this may be slower.",
    requestId: "f6a7b8c9-d0e1-f2a3-b4c5-d6e7f8a9b0c1",
    source: "image-resize",
  },
  {
    id: "log-007",
    timestamp: "2026-03-01T10:52:44.002Z",
    logGroup: "/aws/lambda/image-resize",
    logStream: "2026/03/01/[$LATEST]b2c3d4e5f6a7",
    level: "ERROR",
    message:
      "Failed to read source object: NoSuchKey: The specified key does not exist. Key=uploads/missing-asset.png",
    requestId: "a7b8c9d0-e1f2-a3b4-c5d6-e7f8a9b0c1d2",
    source: "image-resize",
  },
  {
    id: "log-008",
    timestamp: "2026-03-01T10:51:30.500Z",
    logGroup: "/ecs/prod-web",
    logStream: "ecs/prod-web-01/d4e5f6a7b8c9d0e1",
    level: "INFO",
    message:
      "Health check passed: GET /health HTTP/1.1 200 OK — upstream: 10.0.1.15:8080 response_time=12ms",
    source: "prod-web",
  },
  {
    id: "log-009",
    timestamp: "2026-03-01T10:50:15.991Z",
    logGroup: "/ecs/prod-web",
    logStream: "ecs/prod-web-02/e5f6a7b8c9d0e1f2",
    level: "WARN",
    message:
      "Container prod-web-02 memory usage at 89% (1.8GB/2GB). Consider scaling or increasing task definition memory.",
    source: "prod-web",
  },
  {
    id: "log-010",
    timestamp: "2026-03-01T10:49:03.218Z",
    logGroup: "/ecs/prod-web",
    logStream: "ecs/prod-web-01/d4e5f6a7b8c9d0e1",
    level: "ERROR",
    message:
      "Container exited with code 137 (OOMKilled). Task arn:aws:ecs:us-east-1:123456789012:task/prod/f1a2b3 stopped.",
    source: "prod-web",
  },
  {
    id: "log-011",
    timestamp: "2026-03-01T10:48:50.667Z",
    logGroup: "/ecs/prod-web",
    logStream: "ecs/prod-web-01/d4e5f6a7b8c9d0e1",
    level: "INFO",
    message:
      "New task started: arn:aws:ecs:us-east-1:123456789012:task/prod/g2b3c4. Pulling image.",
    source: "prod-web",
  },
  {
    id: "log-012",
    timestamp: "2026-03-01T10:47:22.445Z",
    logGroup: "/aws/apigateway/prod-api",
    logStream: "prod-api/2026/03/01",
    level: "ERROR",
    message:
      "HTTP 502 Bad Gateway: Integration response timeout after 29000ms. Route=POST /api/v2/orders Integration=Lambda:webhook-processor",
    requestId: "b8c9d0e1-f2a3-b4c5-d6e7-f8a9b0c1d2e3",
    source: "apigateway",
  },
  {
    id: "log-013",
    timestamp: "2026-03-01T10:46:14.882Z",
    logGroup: "/aws/apigateway/prod-api",
    logStream: "prod-api/2026/03/01",
    level: "WARN",
    message:
      "HTTP 429 Too Many Requests: throttling limit exceeded for stage prod. Client IP=203.0.113.42 Usage=5000/5000 per minute.",
    requestId: "c9d0e1f2-a3b4-c5d6-e7f8-a9b0c1d2e3f4",
    source: "apigateway",
  },
  {
    id: "log-014",
    timestamp: "2026-03-01T10:45:55.119Z",
    logGroup: "/aws/apigateway/prod-api",
    logStream: "prod-api/2026/03/01",
    level: "INFO",
    message:
      "HTTP 200 OK: GET /api/v2/users/me route=prod-api latency=43ms requestId=d0e1f2a3-b4c5-d6e7-f8a9-b0c1d2e3f4a5",
    requestId: "d0e1f2a3-b4c5-d6e7-f8a9-b0c1d2e3f4a5",
    source: "apigateway",
  },
  {
    id: "log-015",
    timestamp: "2026-03-01T10:44:38.300Z",
    logGroup: "/aws/waf/prod-acl",
    logStream: "waf/prod-acl/2026/03/01",
    level: "WARN",
    message:
      "WAF BLOCK: Rule=AWSManagedRulesSQLiRuleSet/SQLi_BODY action=BLOCK ip=45.227.255.100 country=CN uri=/api/v2/search?q=1%27+OR+1%3D1--",
    source: "waf",
  },
  {
    id: "log-016",
    timestamp: "2026-03-01T10:43:20.778Z",
    logGroup: "/aws/waf/prod-acl",
    logStream: "waf/prod-acl/2026/03/01",
    level: "WARN",
    message:
      "WAF BLOCK: Rule=RateLimitRule action=BLOCK ip=198.51.100.77 country=RU requests=2001 window=5min threshold=2000",
    source: "waf",
  },
  {
    id: "log-017",
    timestamp: "2026-03-01T10:42:05.554Z",
    logGroup: "/aws/waf/prod-acl",
    logStream: "waf/prod-acl/2026/03/01",
    level: "INFO",
    message:
      "WAF ALLOW: Rule=AWSManagedRulesCommonRuleSet/None action=ALLOW ip=1.2.3.4 country=US uri=/api/v2/products",
    source: "waf",
  },
  {
    id: "log-018",
    timestamp: "2026-03-01T10:40:59.001Z",
    logGroup: "/aws/lambda/api-auth-handler",
    logStream: "2026/03/01/[$LATEST]a1b2c3d4e5f6",
    level: "DEBUG",
    message:
      "JWT validation: token_exp=2026-03-01T11:40:59Z now=2026-03-01T10:40:59Z valid=true sub=user_8f2a3b4c",
    requestId: "e1f2a3b4-c5d6-e7f8-a9b0-c1d2e3f4a5b6",
    source: "api-auth-handler",
  },
  {
    id: "log-019",
    timestamp: "2026-03-01T10:39:44.123Z",
    logGroup: "/ecs/prod-web",
    logStream: "ecs/prod-web-02/e5f6a7b8c9d0e1f2",
    level: "DEBUG",
    message:
      "nginx upstream keepalive: pool=10.0.1.20:8080 active=42 idle=8 waiting=0 accepts=18920 handled=18920 requests=104382",
    source: "prod-web",
  },
  {
    id: "log-020",
    timestamp: "2026-03-01T10:38:30.900Z",
    logGroup: "/aws/lambda/api-auth-handler",
    logStream: "2026/03/01/[$LATEST]a1b2c3d4e5f6",
    level: "INFO",
    message:
      "END RequestId: f2a3b4c5-d6e7-f8a9-b0c1-d2e3f4a5b6c7 Duration: 245.32 ms Billed Duration: 246 ms Memory Size: 256 MB Max Memory Used: 178 MB",
    requestId: "f2a3b4c5-d6e7-f8a9-b0c1-d2e3f4a5b6c7",
    source: "api-auth-handler",
  },
  {
    id: "log-021",
    timestamp: "2026-03-01T10:37:12.445Z",
    logGroup: "/aws/apigateway/prod-api",
    logStream: "prod-api/2026/03/01",
    level: "ERROR",
    message:
      "HTTP 500 Internal Server Error: Unhandled exception in Lambda integration. Check CloudWatch logs for function api-auth-handler. requestId=a3b4c5d6-e7f8-a9b0-c1d2-e3f4a5b6c7d8",
    requestId: "a3b4c5d6-e7f8-a9b0-c1d2-e3f4a5b6c7d8",
    source: "apigateway",
  },
  {
    id: "log-022",
    timestamp: "2026-03-01T10:35:00.000Z",
    logGroup: "/ecs/prod-web",
    logStream: "ecs/prod-web-01/d4e5f6a7b8c9d0e1",
    level: "WARN",
    message:
      "Slow response detected: POST /api/v2/checkout upstream=10.0.1.15:8080 response_time=4821ms threshold=2000ms",
    source: "prod-web",
  },
];

export const aiLogAnalysis: AiLogAnalysis = {
  summary:
    "Multiple critical issues detected in the last 2 hours. A Lambda OOM crash on api-auth-handler is causing cascading 500 errors through API Gateway. ECS container instability (OOMKilled exit code 137) suggests insufficient memory allocation across the board.",
  severity: "critical",
  rootCause:
    "Memory pressure across compute resources. Lambda function api-auth-handler is running at the 256 MB limit with peak usage at 178 MB, leaving minimal headroom. The ECS prod-web task is consistently hitting 89%+ memory utilization, triggering kernel OOM killer. These are likely correlated with the observed traffic spike.",
  recommendation:
    "Immediately increase Lambda memory to 512 MB and ECS task definition memory to 3 GB. Enable Lambda Provisioned Concurrency to eliminate cold starts. Set up CloudWatch alarms for memory utilization > 80%. Consider enabling auto-scaling for the ECS service based on memory metrics.",
  relatedPatterns: [
    "OOM errors correlate with traffic peaks between 10:45–11:00 UTC",
    "Cold start warning on api-auth-handler suggests burst traffic",
    "API Gateway 502s are downstream symptoms of Lambda timeouts",
    "WAF rate limiting indicates potential DDoS or scraping activity",
    "image-resize errors on missing S3 keys suggest stale reference data",
  ],
};

// ─── WAF Rule Analysis ────────────────────────────────────────────────────────

export const wafRules: WafRule[] = [
  {
    id: "rule-001",
    name: "AWSManagedRulesCommonRuleSet",
    priority: 1,
    action: "BLOCK",
    type: "MANAGED",
    ruleGroup: "AWS Managed Rules",
    matchesLast24h: 14832,
    blockRate: 94.2,
    enabled: true,
    description:
      "AWS Managed Rules general protection against common web exploits including OWASP Top 10.",
  },
  {
    id: "rule-002",
    name: "AWSManagedRulesSQLiRuleSet",
    priority: 2,
    action: "BLOCK",
    type: "MANAGED",
    ruleGroup: "AWS Managed Rules",
    matchesLast24h: 3204,
    blockRate: 99.8,
    enabled: true,
    description:
      "Protects against SQL injection attacks by inspecting URI, query string, and body.",
  },
  {
    id: "rule-003",
    name: "AWSManagedRulesKnownBadInputsRuleSet",
    priority: 3,
    action: "BLOCK",
    type: "MANAGED",
    ruleGroup: "AWS Managed Rules",
    matchesLast24h: 2118,
    blockRate: 97.1,
    enabled: true,
    description:
      "Blocks request patterns associated with exploitation of vulnerabilities like Log4JRCE.",
  },
  {
    id: "rule-004",
    name: "RateLimitRule-2000rpm",
    priority: 4,
    action: "BLOCK",
    type: "RATE_BASED",
    ruleGroup: "Custom Rules",
    matchesLast24h: 8921,
    blockRate: 72.4,
    enabled: true,
    description: "Rate-based rule: blocks IPs exceeding 2000 requests per 5-minute rolling window.",
  },
  {
    id: "rule-005",
    name: "GeoBlockHighRiskCountries",
    priority: 5,
    action: "BLOCK",
    type: "REGULAR",
    ruleGroup: "Custom Rules",
    matchesLast24h: 5430,
    blockRate: 100.0,
    enabled: true,
    description: "Blocks all traffic originating from high-risk geolocations (CN, RU, KP, IR).",
  },
  {
    id: "rule-006",
    name: "AWSManagedRulesIPReputationList",
    priority: 6,
    action: "BLOCK",
    type: "MANAGED",
    ruleGroup: "AWS Managed Rules",
    matchesLast24h: 1876,
    blockRate: 89.3,
    enabled: true,
    description:
      "Blocks requests from IP addresses with poor reputation based on Amazon threat intelligence.",
  },
  {
    id: "rule-007",
    name: "BotControlManagedRuleSet",
    priority: 7,
    action: "COUNT",
    type: "MANAGED",
    ruleGroup: "AWS Managed Rules",
    matchesLast24h: 6720,
    blockRate: 0.0,
    enabled: true,
    description:
      "Counts bot traffic (verified bots are allowed). Use COUNT mode to monitor before switching to BLOCK.",
  },
  {
    id: "rule-008",
    name: "CustomXSSProtection",
    priority: 8,
    action: "BLOCK",
    type: "REGULAR",
    ruleGroup: "Custom Rules",
    matchesLast24h: 344,
    blockRate: 91.6,
    enabled: false,
    description:
      "Custom XSS protection rule inspecting HTML, script tags in request body and query string.",
  },
];

export const wafWebAcl: WafWebAcl = {
  id: "acl-0a1b2c3d4e5f6g7h8",
  name: "prod-web-acl",
  region: "us-east-1",
  rulesCount: 8,
  requestsSampled: 284920,
  blockedRequests: 43505,
  allowedRequests: 241415,
};

export const wafTraffic: WafTrafficData[] = [
  { time: "00:00", allowed: 7820, blocked: 820, counted: 340 },
  { time: "01:00", allowed: 6450, blocked: 710, counted: 290 },
  { time: "02:00", allowed: 5120, blocked: 640, counted: 210 },
  { time: "03:00", allowed: 4380, blocked: 580, counted: 180 },
  { time: "04:00", allowed: 4110, blocked: 560, counted: 170 },
  { time: "05:00", allowed: 5540, blocked: 690, counted: 240 },
  { time: "06:00", allowed: 8930, blocked: 1020, counted: 410 },
  { time: "07:00", allowed: 11200, blocked: 1340, counted: 520 },
  { time: "08:00", allowed: 14850, blocked: 1780, counted: 640 },
  { time: "09:00", allowed: 16420, blocked: 2010, counted: 710 },
  { time: "10:00", allowed: 17840, blocked: 2240, counted: 820 },
  { time: "11:00", allowed: 18320, blocked: 10450, counted: 890 },
  { time: "12:00", allowed: 15200, blocked: 3120, counted: 780 },
  { time: "13:00", allowed: 16080, blocked: 2580, counted: 810 },
  { time: "14:00", allowed: 17500, blocked: 2190, counted: 850 },
  { time: "15:00", allowed: 17100, blocked: 2050, counted: 830 },
  { time: "16:00", allowed: 15700, blocked: 1870, counted: 760 },
  { time: "17:00", allowed: 13400, blocked: 1620, counted: 680 },
  { time: "18:00", allowed: 11200, blocked: 1380, counted: 590 },
  { time: "19:00", allowed: 9800, blocked: 1180, counted: 480 },
  { time: "20:00", allowed: 10200, blocked: 1240, counted: 510 },
  { time: "21:00", allowed: 9100, blocked: 1080, counted: 440 },
  { time: "22:00", allowed: 8400, blocked: 960, counted: 390 },
  { time: "23:00", allowed: 7900, blocked: 880, counted: 360 },
];

export const wafTopThreats: WafTopThreat[] = [
  {
    source: "45.227.255.100",
    country: "🇨🇳 China",
    requests: 8420,
    blocked: 8420,
    ruleTriggered: "GeoBlockHighRiskCountries",
  },
  {
    source: "198.51.100.77",
    country: "🇷🇺 Russia",
    requests: 6210,
    blocked: 6210,
    ruleTriggered: "RateLimitRule-2000rpm",
  },
  {
    source: "203.0.113.42",
    country: "🇧🇷 Brazil",
    requests: 5880,
    blocked: 4244,
    ruleTriggered: "AWSManagedRulesSQLiRuleSet",
  },
  {
    source: "192.0.2.88",
    country: "🇩🇪 Germany",
    requests: 3920,
    blocked: 1960,
    ruleTriggered: "RateLimitRule-2000rpm",
  },
  {
    source: "185.220.101.44",
    country: "🇳🇱 Netherlands",
    requests: 2840,
    blocked: 2756,
    ruleTriggered: "AWSManagedRulesIPReputationList",
  },
  {
    source: "103.75.190.12",
    country: "🇮🇳 India",
    requests: 2210,
    blocked: 884,
    ruleTriggered: "AWSManagedRulesCommonRuleSet",
  },
];

// ─── Jenkins CI/CD ────────────────────────────────────────────────────────────

export const jenkinsServer: JenkinsServerInfo = {
  url: "https://jenkins.internal.company.com",
  version: "2.462.1",
  connected: true,
  nodeCount: 5,
  executorsBusy: 3,
  executorsTotal: 8,
  queueLength: 2,
};

export const jenkinsJobs: JenkinsJob[] = [
  {
    name: "deploy-prod-web",
    fullName: "deployments/deploy-prod-web",
    url: "https://jenkins.internal.company.com/job/deployments/job/deploy-prod-web",
    type: "pipeline",
    healthScore: 80,
    enabled: true,
    description: "Deploys web frontend to ECS production cluster using blue-green strategy",
    lastBuild: {
      number: 487,
      status: "SUCCESS",
      timestamp: "2026-03-01T09:42:00Z",
      durationMs: 187000,
      trigger: "Started by user admin",
      stages: [
        { name: "Checkout", status: "SUCCESS", durationMs: 3200 },
        { name: "Build", status: "SUCCESS", durationMs: 42000 },
        { name: "Test", status: "SUCCESS", durationMs: 68000 },
        { name: "Deploy to ECS", status: "SUCCESS", durationMs: 61000 },
        { name: "Smoke Test", status: "SUCCESS", durationMs: 12800 },
      ],
    },
  },
  {
    name: "deploy-staging-web",
    fullName: "deployments/deploy-staging-web",
    url: "https://jenkins.internal.company.com/job/deployments/job/deploy-staging-web",
    type: "pipeline",
    healthScore: 100,
    enabled: true,
    description: "Deploys web frontend to ECS staging environment on every commit to develop",
    lastBuild: {
      number: 312,
      status: "SUCCESS",
      timestamp: "2026-03-01T10:15:00Z",
      durationMs: 142000,
      trigger: "Started by an SCM change",
      stages: [
        { name: "Checkout", status: "SUCCESS", durationMs: 2800 },
        { name: "Build", status: "SUCCESS", durationMs: 38000 },
        { name: "Test", status: "SUCCESS", durationMs: 55000 },
        { name: "Deploy to ECS", status: "SUCCESS", durationMs: 40000 },
        { name: "Smoke Test", status: "SUCCESS", durationMs: 6200 },
      ],
    },
  },
  {
    name: "deploy-prod-api",
    fullName: "deployments/deploy-prod-api",
    url: "https://jenkins.internal.company.com/job/deployments/job/deploy-prod-api",
    type: "pipeline",
    healthScore: 60,
    enabled: true,
    description: "Deploys API backend to ECS production using canary deployment strategy",
    lastBuild: {
      number: 398,
      status: "FAILURE",
      timestamp: "2026-03-01T08:30:00Z",
      durationMs: 215000,
      trigger: "Started by user admin",
      stages: [
        { name: "Checkout", status: "SUCCESS", durationMs: 3100 },
        { name: "Build", status: "SUCCESS", durationMs: 44000 },
        { name: "Unit Test", status: "SUCCESS", durationMs: 72000 },
        { name: "Integration Test", status: "SUCCESS", durationMs: 48000 },
        { name: "Deploy to ECS", status: "FAILURE", durationMs: 47900 },
        { name: "Health Check", status: "ABORTED", durationMs: 0 },
      ],
    },
  },
  {
    name: "deploy-lambda-functions",
    fullName: "deployments/deploy-lambda-functions",
    url: "https://jenkins.internal.company.com/job/deployments/job/deploy-lambda-functions",
    type: "pipeline",
    healthScore: 90,
    enabled: true,
    description: "Packages and deploys all Lambda functions using SAM CLI",
    lastBuild: {
      number: 203,
      status: "SUCCESS",
      timestamp: "2026-03-01T07:55:00Z",
      durationMs: 98000,
      trigger: "Started by timer",
      stages: [
        { name: "Checkout", status: "SUCCESS", durationMs: 2500 },
        { name: "Build", status: "SUCCESS", durationMs: 28000 },
        { name: "Package", status: "SUCCESS", durationMs: 18000 },
        { name: "Deploy to Lambda", status: "SUCCESS", durationMs: 44000 },
        { name: "Verify", status: "SUCCESS", durationMs: 5500 },
      ],
    },
  },
  {
    name: "infra-terraform-plan",
    fullName: "infrastructure/infra-terraform-plan",
    url: "https://jenkins.internal.company.com/job/infrastructure/job/infra-terraform-plan",
    type: "pipeline",
    healthScore: 100,
    enabled: true,
    description: "Runs Terraform plan and apply for core infrastructure changes with approval gate",
    lastBuild: {
      number: 156,
      status: "SUCCESS",
      timestamp: "2026-02-29T14:20:00Z",
      durationMs: 302000,
      trigger: "Started by user ops-mike",
      stages: [
        { name: "Checkout", status: "SUCCESS", durationMs: 2900 },
        { name: "Init", status: "SUCCESS", durationMs: 12000 },
        { name: "Plan", status: "SUCCESS", durationMs: 35000 },
        { name: "Approval", status: "SUCCESS", durationMs: 240000 },
        { name: "Apply", status: "SUCCESS", durationMs: 12100 },
      ],
    },
  },
  {
    name: "db-migration-runner",
    fullName: "database/db-migration-runner",
    url: "https://jenkins.internal.company.com/job/database/job/db-migration-runner",
    type: "freestyle",
    healthScore: 70,
    enabled: true,
    description: "Runs database migrations against the target environment using Flyway",
    lastBuild: {
      number: 89,
      status: "UNSTABLE",
      timestamp: "2026-03-01T06:00:00Z",
      durationMs: 54000,
      trigger: "Started by timer",
      stages: [
        { name: "Checkout", status: "SUCCESS", durationMs: 2200 },
        { name: "Validate", status: "SUCCESS", durationMs: 8000 },
        { name: "Migrate", status: "UNSTABLE", durationMs: 43800 },
      ],
    },
  },
];

export const deployConfigs: DeployConfig[] = [
  {
    id: "dc-001",
    name: "Web Frontend (Prod)",
    jenkinsJob: "deploy-prod-web",
    targetEnv: "prod",
    targetService: "web-frontend",
    awsRegion: "us-east-1",
    deployStrategy: "blue-green",
    autoApprove: false,
    lastDeployed: "2026-03-01T09:42:00Z",
    lastStatus: "SUCCESS",
    parameters: [
      {
        name: "IMAGE_TAG",
        type: "string",
        defaultValue: "latest",
        description: "Docker image tag to deploy",
      },
      {
        name: "SKIP_TESTS",
        type: "boolean",
        defaultValue: "false",
        description: "Skip smoke tests after deployment",
      },
      {
        name: "ROLLBACK_ON_FAIL",
        type: "boolean",
        defaultValue: "true",
        description: "Automatically rollback if health checks fail",
      },
    ],
  },
  {
    id: "dc-002",
    name: "Web Frontend (Staging)",
    jenkinsJob: "deploy-staging-web",
    targetEnv: "staging",
    targetService: "web-frontend-staging",
    awsRegion: "us-east-1",
    deployStrategy: "rolling",
    autoApprove: true,
    lastDeployed: "2026-03-01T10:15:00Z",
    lastStatus: "SUCCESS",
    parameters: [
      {
        name: "IMAGE_TAG",
        type: "string",
        defaultValue: "develop",
        description: "Docker image tag to deploy",
      },
      {
        name: "BRANCH",
        type: "choice",
        defaultValue: "main",
        description: "Source branch to build and deploy",
        choices: ["main", "develop", "feature"],
      },
    ],
  },
  {
    id: "dc-003",
    name: "API Backend (Prod)",
    jenkinsJob: "deploy-prod-api",
    targetEnv: "prod",
    targetService: "api-backend",
    awsRegion: "us-east-1",
    deployStrategy: "canary",
    autoApprove: false,
    lastDeployed: "2026-03-01T08:30:00Z",
    lastStatus: "FAILURE",
    parameters: [
      {
        name: "IMAGE_TAG",
        type: "string",
        defaultValue: "latest",
        description: "Docker image tag to deploy",
      },
      {
        name: "CANARY_WEIGHT",
        type: "choice",
        defaultValue: "10%",
        description: "Percentage of traffic to route to canary",
        choices: ["10%", "25%", "50%", "100%"],
      },
    ],
  },
  {
    id: "dc-004",
    name: "Lambda Functions",
    jenkinsJob: "deploy-lambda-functions",
    targetEnv: "prod",
    targetService: "all-functions",
    awsRegion: "us-east-1",
    deployStrategy: "rolling",
    autoApprove: true,
    lastDeployed: "2026-03-01T07:55:00Z",
    lastStatus: "SUCCESS",
    parameters: [
      {
        name: "FUNCTION_FILTER",
        type: "string",
        defaultValue: "*",
        description: "Glob pattern to filter which functions to deploy",
      },
      {
        name: "DRY_RUN",
        type: "boolean",
        defaultValue: "false",
        description: "Perform a dry run without actually deploying",
      },
    ],
  },
  {
    id: "dc-005",
    name: "Infrastructure",
    jenkinsJob: "infra-terraform-plan",
    targetEnv: "prod",
    targetService: "core-infra",
    awsRegion: "us-east-1",
    deployStrategy: "rolling",
    autoApprove: false,
    lastDeployed: "2026-02-29T14:20:00Z",
    lastStatus: "SUCCESS",
    parameters: [
      {
        name: "TF_WORKSPACE",
        type: "choice",
        defaultValue: "prod",
        description: "Terraform workspace to operate on",
        choices: ["dev", "staging", "prod"],
      },
      {
        name: "AUTO_APPROVE",
        type: "boolean",
        defaultValue: "false",
        description: "Skip Terraform plan approval gate",
      },
    ],
  },
];

export const jenkinsQueue: JenkinsQueueItem[] = [
  {
    id: 1,
    jobName: "deploy-staging-web",
    reason: "Waiting for next available executor on agent node-02",
    inQueueSince: "2026-03-01T10:58:00Z",
    estimatedDuration: 142000,
  },
  {
    id: 2,
    jobName: "db-migration-runner",
    reason: "Build #90 is already in progress, waiting for it to complete",
    inQueueSince: "2026-03-01T10:59:30Z",
    estimatedDuration: 54000,
  },
];

export const jenkinsBuildHistory: JenkinsBuild[] = [
  {
    number: 487,
    status: "SUCCESS",
    timestamp: "2026-03-01T09:42:00Z",
    durationMs: 187000,
    trigger: "Started by user admin",
    stages: [
      { name: "Checkout", status: "SUCCESS", durationMs: 3200 },
      { name: "Build", status: "SUCCESS", durationMs: 42000 },
      { name: "Test", status: "SUCCESS", durationMs: 68000 },
      { name: "Deploy to ECS", status: "SUCCESS", durationMs: 61000 },
      { name: "Smoke Test", status: "SUCCESS", durationMs: 12800 },
    ],
  },
  {
    number: 486,
    status: "FAILURE",
    timestamp: "2026-03-01T07:10:00Z",
    durationMs: 124000,
    trigger: "Started by an SCM change",
    stages: [
      { name: "Checkout", status: "SUCCESS", durationMs: 3100 },
      { name: "Build", status: "SUCCESS", durationMs: 41000 },
      { name: "Test", status: "FAILURE", durationMs: 79900 },
      { name: "Deploy to ECS", status: "ABORTED", durationMs: 0 },
      { name: "Smoke Test", status: "ABORTED", durationMs: 0 },
    ],
  },
  {
    number: 485,
    status: "SUCCESS",
    timestamp: "2026-03-01T04:30:00Z",
    durationMs: 192000,
    trigger: "Started by timer",
    stages: [
      { name: "Checkout", status: "SUCCESS", durationMs: 3400 },
      { name: "Build", status: "SUCCESS", durationMs: 45000 },
      { name: "Test", status: "SUCCESS", durationMs: 71000 },
      { name: "Deploy to ECS", status: "SUCCESS", durationMs: 59000 },
      { name: "Smoke Test", status: "SUCCESS", durationMs: 13600 },
    ],
  },
  {
    number: 484,
    status: "SUCCESS",
    timestamp: "2026-02-29T22:15:00Z",
    durationMs: 178000,
    trigger: "Started by user dev-sarah",
    stages: [
      { name: "Checkout", status: "SUCCESS", durationMs: 2900 },
      { name: "Build", status: "SUCCESS", durationMs: 39000 },
      { name: "Test", status: "SUCCESS", durationMs: 64000 },
      { name: "Deploy to ECS", status: "SUCCESS", durationMs: 60000 },
      { name: "Smoke Test", status: "SUCCESS", durationMs: 12100 },
    ],
  },
  {
    number: 483,
    status: "UNSTABLE",
    timestamp: "2026-02-29T19:05:00Z",
    durationMs: 201000,
    trigger: "Started by an SCM change",
    stages: [
      { name: "Checkout", status: "SUCCESS", durationMs: 3000 },
      { name: "Build", status: "SUCCESS", durationMs: 43000 },
      { name: "Test", status: "UNSTABLE", durationMs: 85000 },
      { name: "Deploy to ECS", status: "SUCCESS", durationMs: 58000 },
      { name: "Smoke Test", status: "SUCCESS", durationMs: 12000 },
    ],
  },
  {
    number: 482,
    status: "SUCCESS",
    timestamp: "2026-02-29T16:30:00Z",
    durationMs: 183000,
    trigger: "Started by user ops-mike",
    stages: [
      { name: "Checkout", status: "SUCCESS", durationMs: 3100 },
      { name: "Build", status: "SUCCESS", durationMs: 40000 },
      { name: "Test", status: "SUCCESS", durationMs: 67000 },
      { name: "Deploy to ECS", status: "SUCCESS", durationMs: 60000 },
      { name: "Smoke Test", status: "SUCCESS", durationMs: 12900 },
    ],
  },
  {
    number: 481,
    status: "SUCCESS",
    timestamp: "2026-02-29T13:00:00Z",
    durationMs: 189000,
    trigger: "Started by an SCM change",
    stages: [
      { name: "Checkout", status: "SUCCESS", durationMs: 2700 },
      { name: "Build", status: "SUCCESS", durationMs: 41000 },
      { name: "Test", status: "SUCCESS", durationMs: 70000 },
      { name: "Deploy to ECS", status: "SUCCESS", durationMs: 63000 },
      { name: "Smoke Test", status: "SUCCESS", durationMs: 12300 },
    ],
  },
  {
    number: 480,
    status: "ABORTED",
    timestamp: "2026-02-29T10:45:00Z",
    durationMs: 41000,
    trigger: "Started by user admin",
    stages: [
      { name: "Checkout", status: "SUCCESS", durationMs: 3000 },
      { name: "Build", status: "ABORTED", durationMs: 38000 },
      { name: "Test", status: "ABORTED", durationMs: 0 },
      { name: "Deploy to ECS", status: "ABORTED", durationMs: 0 },
      { name: "Smoke Test", status: "ABORTED", durationMs: 0 },
    ],
  },
  {
    number: 479,
    status: "SUCCESS",
    timestamp: "2026-02-29T08:20:00Z",
    durationMs: 176000,
    trigger: "Started by timer",
    stages: [
      { name: "Checkout", status: "SUCCESS", durationMs: 2800 },
      { name: "Build", status: "SUCCESS", durationMs: 38000 },
      { name: "Test", status: "SUCCESS", durationMs: 63000 },
      { name: "Deploy to ECS", status: "SUCCESS", durationMs: 59000 },
      { name: "Smoke Test", status: "SUCCESS", durationMs: 13200 },
    ],
  },
  {
    number: 478,
    status: "FAILURE",
    timestamp: "2026-02-29T05:00:00Z",
    durationMs: 98000,
    trigger: "Started by an SCM change",
    stages: [
      { name: "Checkout", status: "SUCCESS", durationMs: 3300 },
      { name: "Build", status: "FAILURE", durationMs: 94700 },
      { name: "Test", status: "ABORTED", durationMs: 0 },
      { name: "Deploy to ECS", status: "ABORTED", durationMs: 0 },
      { name: "Smoke Test", status: "ABORTED", durationMs: 0 },
    ],
  },
];

// ── ECS Data ───────────────────────────────────────────────

export const ecsClusters: ECSCluster[] = [
  {
    name: "prod-cluster",
    arn: "arn:aws:ecs:us-east-1:123456789012:cluster/prod-cluster",
    status: "ACTIVE",
    registeredInstances: 8,
    runningTasks: 47,
    pendingTasks: 3,
    activeServices: 12,
    cpuReservation: 62,
    memoryReservation: 58,
    cpuUtilization: 41,
    memoryUtilization: 53,
  },
  {
    name: "staging-cluster",
    arn: "arn:aws:ecs:us-east-1:123456789012:cluster/staging-cluster",
    status: "ACTIVE",
    registeredInstances: 3,
    runningTasks: 14,
    pendingTasks: 0,
    activeServices: 6,
    cpuReservation: 38,
    memoryReservation: 42,
    cpuUtilization: 22,
    memoryUtilization: 31,
  },
  {
    name: "dev-cluster",
    arn: "arn:aws:ecs:us-east-1:123456789012:cluster/dev-cluster",
    status: "ACTIVE",
    registeredInstances: 2,
    runningTasks: 8,
    pendingTasks: 1,
    activeServices: 4,
    cpuReservation: 25,
    memoryReservation: 30,
    cpuUtilization: 12,
    memoryUtilization: 18,
  },
];

export const ecsServices: ECSService[] = [
  {
    name: "api-service",
    arn: "arn:aws:ecs:us-east-1:123456789012:service/prod-cluster/api-service",
    clusterName: "prod-cluster",
    status: "ACTIVE",
    health: "HEALTHY",
    taskDefinition: "api-service:45",
    desiredCount: 5,
    runningCount: 5,
    pendingCount: 0,
    launchType: "FARGATE",
    deployments: [
      {
        id: "ecs-svc/dep-001",
        status: "PRIMARY",
        rolloutState: "COMPLETED",
        taskDefinition: "api-service:45",
        desiredCount: 5,
        runningCount: 5,
        pendingCount: 0,
        createdAt: "2026-02-28T14:30:00Z",
        updatedAt: "2026-02-28T14:35:00Z",
      },
    ],
    loadBalancerTarget:
      "arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/api-tg/abc123",
    scaling: {
      enabled: true,
      minCapacity: 2,
      maxCapacity: 10,
      policies: [
        {
          policyName: "cpu-tracking",
          metricType: "CPU",
          targetValue: 70,
          scaleUpCooldown: 60,
          scaleDownCooldown: 300,
        },
      ],
    },
    cpuUtilization: 35,
    memoryUtilization: 48,
    createdAt: "2025-06-15T10:00:00Z",
    lastDeployment: "2026-02-28T14:30:00Z",
    updatedBy: "jenkins/deploy-pipeline",
  },
  {
    name: "web-frontend",
    arn: "arn:aws:ecs:us-east-1:123456789012:service/prod-cluster/web-frontend",
    clusterName: "prod-cluster",
    status: "ACTIVE",
    health: "HEALTHY",
    taskDefinition: "web-frontend:32",
    desiredCount: 4,
    runningCount: 4,
    pendingCount: 0,
    launchType: "FARGATE",
    deployments: [
      {
        id: "ecs-svc/dep-002",
        status: "PRIMARY",
        rolloutState: "COMPLETED",
        taskDefinition: "web-frontend:32",
        desiredCount: 4,
        runningCount: 4,
        pendingCount: 0,
        createdAt: "2026-02-28T10:00:00Z",
        updatedAt: "2026-02-28T10:04:00Z",
      },
    ],
    loadBalancerTarget:
      "arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/web-tg/def456",
    scaling: {
      enabled: true,
      minCapacity: 2,
      maxCapacity: 8,
      policies: [
        {
          policyName: "request-count-tracking",
          metricType: "ALBRequestCount",
          targetValue: 1000,
          scaleUpCooldown: 60,
          scaleDownCooldown: 120,
        },
      ],
    },
    cpuUtilization: 28,
    memoryUtilization: 42,
    createdAt: "2025-06-15T10:00:00Z",
    lastDeployment: "2026-02-28T10:00:00Z",
    updatedBy: "jenkins/deploy-pipeline",
  },
  {
    name: "api-v2",
    arn: "arn:aws:ecs:us-east-1:123456789012:service/prod-cluster/api-v2",
    clusterName: "prod-cluster",
    status: "ACTIVE",
    health: "ROLLING",
    taskDefinition: "api-v2:18",
    desiredCount: 3,
    runningCount: 2,
    pendingCount: 1,
    launchType: "FARGATE",
    deployments: [
      {
        id: "ecs-svc/dep-003a",
        status: "PRIMARY",
        rolloutState: "IN_PROGRESS",
        taskDefinition: "api-v2:18",
        desiredCount: 3,
        runningCount: 2,
        pendingCount: 1,
        createdAt: "2026-03-01T14:35:00Z",
        updatedAt: "2026-03-01T14:38:00Z",
      },
      {
        id: "ecs-svc/dep-003b",
        status: "ACTIVE",
        rolloutState: "COMPLETED",
        taskDefinition: "api-v2:17",
        desiredCount: 0,
        runningCount: 1,
        pendingCount: 0,
        createdAt: "2026-02-27T09:00:00Z",
        updatedAt: "2026-02-27T09:05:00Z",
      },
    ],
    loadBalancerTarget:
      "arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/api-v2-tg/ghi789",
    scaling: {
      enabled: true,
      minCapacity: 2,
      maxCapacity: 6,
      policies: [
        {
          policyName: "cpu-tracking",
          metricType: "CPU",
          targetValue: 65,
          scaleUpCooldown: 60,
          scaleDownCooldown: 300,
        },
        {
          policyName: "memory-tracking",
          metricType: "Memory",
          targetValue: 80,
          scaleUpCooldown: 60,
          scaleDownCooldown: 300,
        },
      ],
    },
    cpuUtilization: 52,
    memoryUtilization: 61,
    createdAt: "2025-11-01T08:00:00Z",
    lastDeployment: "2026-03-01T14:35:00Z",
    updatedBy: "admin@company.com",
  },
  {
    name: "background-jobs",
    arn: "arn:aws:ecs:us-east-1:123456789012:service/prod-cluster/background-jobs",
    clusterName: "prod-cluster",
    status: "ACTIVE",
    health: "HEALTHY",
    taskDefinition: "background-jobs:21",
    desiredCount: 2,
    runningCount: 2,
    pendingCount: 0,
    launchType: "EC2",
    deployments: [
      {
        id: "ecs-svc/dep-004",
        status: "PRIMARY",
        rolloutState: "COMPLETED",
        taskDefinition: "background-jobs:21",
        desiredCount: 2,
        runningCount: 2,
        pendingCount: 0,
        createdAt: "2026-02-26T16:00:00Z",
        updatedAt: "2026-02-26T16:08:00Z",
      },
    ],
    loadBalancerTarget: null,
    scaling: {
      enabled: false,
      minCapacity: 2,
      maxCapacity: 2,
      policies: [],
    },
    cpuUtilization: 68,
    memoryUtilization: 72,
    createdAt: "2025-08-20T12:00:00Z",
    lastDeployment: "2026-02-26T16:00:00Z",
    updatedBy: "jenkins/deploy-pipeline",
  },
  {
    name: "cache-warmer",
    arn: "arn:aws:ecs:us-east-1:123456789012:service/prod-cluster/cache-warmer",
    clusterName: "prod-cluster",
    status: "ACTIVE",
    health: "UNHEALTHY",
    taskDefinition: "cache-warmer:8",
    desiredCount: 1,
    runningCount: 0,
    pendingCount: 1,
    launchType: "FARGATE",
    deployments: [
      {
        id: "ecs-svc/dep-005",
        status: "PRIMARY",
        rolloutState: "FAILED",
        taskDefinition: "cache-warmer:8",
        desiredCount: 1,
        runningCount: 0,
        pendingCount: 1,
        createdAt: "2026-03-01T12:00:00Z",
        updatedAt: "2026-03-01T12:15:00Z",
      },
    ],
    loadBalancerTarget: null,
    scaling: {
      enabled: false,
      minCapacity: 1,
      maxCapacity: 1,
      policies: [],
    },
    cpuUtilization: 0,
    memoryUtilization: 0,
    createdAt: "2026-01-10T09:00:00Z",
    lastDeployment: "2026-03-01T12:00:00Z",
    updatedBy: "admin@company.com",
  },
  {
    name: "payment-processor",
    arn: "arn:aws:ecs:us-east-1:123456789012:service/prod-cluster/payment-processor",
    clusterName: "prod-cluster",
    status: "ACTIVE",
    health: "SCALING",
    taskDefinition: "payment-processor:12",
    desiredCount: 6,
    runningCount: 4,
    pendingCount: 2,
    launchType: "FARGATE",
    deployments: [
      {
        id: "ecs-svc/dep-006",
        status: "PRIMARY",
        rolloutState: "COMPLETED",
        taskDefinition: "payment-processor:12",
        desiredCount: 6,
        runningCount: 4,
        pendingCount: 2,
        createdAt: "2026-02-25T11:00:00Z",
        updatedAt: "2026-03-01T14:30:00Z",
      },
    ],
    loadBalancerTarget:
      "arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/pay-tg/jkl012",
    scaling: {
      enabled: true,
      minCapacity: 3,
      maxCapacity: 12,
      policies: [
        {
          policyName: "cpu-tracking",
          metricType: "CPU",
          targetValue: 60,
          scaleUpCooldown: 30,
          scaleDownCooldown: 300,
        },
      ],
    },
    cpuUtilization: 78,
    memoryUtilization: 65,
    createdAt: "2025-09-01T08:00:00Z",
    lastDeployment: "2026-02-25T11:00:00Z",
    updatedBy: "jenkins/deploy-pipeline",
  },
];

export const ecsTasks: ECSTask[] = [
  {
    taskId: "a1b2c3d4e5f6",
    taskDefinition: "api-service:45",
    serviceName: "api-service",
    clusterName: "prod-cluster",
    status: "RUNNING",
    healthStatus: "HEALTHY",
    cpu: 512,
    memory: 1024,
    cpuUtilization: 32,
    memoryUtilization: 48,
    containers: [
      {
        name: "api",
        image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/api-service:v2.5.1",
        cpu: 512,
        memory: 1024,
        status: "RUNNING",
        healthStatus: "HEALTHY",
        lastStartedAt: "2026-02-28T14:32:00Z",
      },
    ],
    startedAt: "2026-02-28T14:32:00Z",
    stoppedAt: null,
    stoppedReason: null,
    launchType: "FARGATE",
    privateIp: "10.0.1.45",
  },
  {
    taskId: "b2c3d4e5f6g7",
    taskDefinition: "api-service:45",
    serviceName: "api-service",
    clusterName: "prod-cluster",
    status: "RUNNING",
    healthStatus: "HEALTHY",
    cpu: 512,
    memory: 1024,
    cpuUtilization: 38,
    memoryUtilization: 52,
    containers: [
      {
        name: "api",
        image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/api-service:v2.5.1",
        cpu: 512,
        memory: 1024,
        status: "RUNNING",
        healthStatus: "HEALTHY",
        lastStartedAt: "2026-02-28T14:33:00Z",
      },
    ],
    startedAt: "2026-02-28T14:33:00Z",
    stoppedAt: null,
    stoppedReason: null,
    launchType: "FARGATE",
    privateIp: "10.0.1.46",
  },
  {
    taskId: "c3d4e5f6g7h8",
    taskDefinition: "api-v2:18",
    serviceName: "api-v2",
    clusterName: "prod-cluster",
    status: "PENDING",
    healthStatus: "UNKNOWN",
    cpu: 1024,
    memory: 2048,
    cpuUtilization: 0,
    memoryUtilization: 0,
    containers: [
      {
        name: "api-v2",
        image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/api-v2:v3.0.0-rc1",
        cpu: 1024,
        memory: 2048,
        status: "PENDING",
        healthStatus: "UNKNOWN",
        lastStartedAt: "2026-03-01T14:36:00Z",
      },
    ],
    startedAt: "2026-03-01T14:36:00Z",
    stoppedAt: null,
    stoppedReason: null,
    launchType: "FARGATE",
    privateIp: "10.0.2.12",
  },
  {
    taskId: "d4e5f6g7h8i9",
    taskDefinition: "web-frontend:32",
    serviceName: "web-frontend",
    clusterName: "prod-cluster",
    status: "RUNNING",
    healthStatus: "HEALTHY",
    cpu: 256,
    memory: 512,
    cpuUtilization: 18,
    memoryUtilization: 35,
    containers: [
      {
        name: "nginx",
        image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/web-frontend:v4.1.0",
        cpu: 256,
        memory: 512,
        status: "RUNNING",
        healthStatus: "HEALTHY",
        lastStartedAt: "2026-02-28T10:02:00Z",
      },
    ],
    startedAt: "2026-02-28T10:02:00Z",
    stoppedAt: null,
    stoppedReason: null,
    launchType: "FARGATE",
    privateIp: "10.0.1.80",
  },
  {
    taskId: "e5f6g7h8i9j0",
    taskDefinition: "background-jobs:21",
    serviceName: "background-jobs",
    clusterName: "prod-cluster",
    status: "RUNNING",
    healthStatus: "HEALTHY",
    cpu: 2048,
    memory: 4096,
    cpuUtilization: 72,
    memoryUtilization: 68,
    containers: [
      {
        name: "worker",
        image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/background-jobs:v1.8.3",
        cpu: 1024,
        memory: 2048,
        status: "RUNNING",
        healthStatus: "HEALTHY",
        lastStartedAt: "2026-02-26T16:04:00Z",
      },
      {
        name: "sidecar",
        image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/datadog-agent:7.45",
        cpu: 1024,
        memory: 2048,
        status: "RUNNING",
        healthStatus: "HEALTHY",
        lastStartedAt: "2026-02-26T16:04:00Z",
      },
    ],
    startedAt: "2026-02-26T16:04:00Z",
    stoppedAt: null,
    stoppedReason: null,
    launchType: "EC2",
    privateIp: "10.0.3.22",
  },
  {
    taskId: "f6g7h8i9j0k1",
    taskDefinition: "cache-warmer:8",
    serviceName: "cache-warmer",
    clusterName: "prod-cluster",
    status: "STOPPED",
    healthStatus: "UNHEALTHY",
    cpu: 256,
    memory: 512,
    cpuUtilization: 0,
    memoryUtilization: 0,
    containers: [
      {
        name: "warmer",
        image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/cache-warmer:v1.2.0",
        cpu: 256,
        memory: 512,
        status: "STOPPED",
        healthStatus: "UNHEALTHY",
        lastStartedAt: "2026-03-01T12:02:00Z",
      },
    ],
    startedAt: "2026-03-01T12:02:00Z",
    stoppedAt: "2026-03-01T12:14:00Z",
    stoppedReason: "Essential container in task exited (exit code: 137 - OOMKilled)",
    launchType: "FARGATE",
    privateIp: "10.0.1.99",
  },
  {
    taskId: "g7h8i9j0k1l2",
    taskDefinition: "payment-processor:12",
    serviceName: "payment-processor",
    clusterName: "prod-cluster",
    status: "PROVISIONING",
    healthStatus: "UNKNOWN",
    cpu: 1024,
    memory: 2048,
    cpuUtilization: 0,
    memoryUtilization: 0,
    containers: [
      {
        name: "processor",
        image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/payment-processor:v5.0.2",
        cpu: 1024,
        memory: 2048,
        status: "PENDING",
        healthStatus: "UNKNOWN",
        lastStartedAt: "2026-03-01T14:31:00Z",
      },
    ],
    startedAt: "2026-03-01T14:31:00Z",
    stoppedAt: null,
    stoppedReason: null,
    launchType: "FARGATE",
    privateIp: "10.0.2.55",
  },
];

export const ecsEvents: ECSEvent[] = [
  {
    id: "evt-001",
    timestamp: "2026-03-01T14:35:00Z",
    serviceName: "api-v2",
    clusterName: "prod-cluster",
    message: "service api-v2 has started 1 task: task c3d4e5f6g7h8.",
    type: "DEPLOYMENT",
  },
  {
    id: "evt-002",
    timestamp: "2026-03-01T14:31:00Z",
    serviceName: "payment-processor",
    clusterName: "prod-cluster",
    message: "service payment-processor has begun scaling activity: desired=6, running=4.",
    type: "SCALING",
  },
  {
    id: "evt-003",
    timestamp: "2026-03-01T14:14:00Z",
    serviceName: "cache-warmer",
    clusterName: "prod-cluster",
    message:
      "service cache-warmer task f6g7h8i9j0k1 stopped: Essential container exited (OOMKilled).",
    type: "ERROR",
  },
  {
    id: "evt-004",
    timestamp: "2026-03-01T12:00:00Z",
    serviceName: "cache-warmer",
    clusterName: "prod-cluster",
    message:
      "service cache-warmer deployment ecs-svc/dep-005 circuit breaker triggered. Rollback started.",
    type: "ERROR",
  },
  {
    id: "evt-005",
    timestamp: "2026-02-28T14:35:00Z",
    serviceName: "api-service",
    clusterName: "prod-cluster",
    message:
      "service api-service has reached a steady state. Deployment ecs-svc/dep-001 completed.",
    type: "DEPLOYMENT",
  },
  {
    id: "evt-006",
    timestamp: "2026-02-28T14:30:00Z",
    serviceName: "api-service",
    clusterName: "prod-cluster",
    message:
      "service api-service deployment ecs-svc/dep-001 started: rolling update to api-service:45.",
    type: "DEPLOYMENT",
  },
  {
    id: "evt-007",
    timestamp: "2026-02-28T10:04:00Z",
    serviceName: "web-frontend",
    clusterName: "prod-cluster",
    message:
      "service web-frontend has reached a steady state. Deployment ecs-svc/dep-002 completed.",
    type: "DEPLOYMENT",
  },
  {
    id: "evt-008",
    timestamp: "2026-02-28T09:45:00Z",
    serviceName: "background-jobs",
    clusterName: "prod-cluster",
    message:
      "service background-jobs task e5f6g7h8i9j0 was restarted due to a health check failure.",
    type: "TASK",
  },
  {
    id: "evt-009",
    timestamp: "2026-02-27T15:30:00Z",
    serviceName: "payment-processor",
    clusterName: "prod-cluster",
    message:
      "service payment-processor scaled down from 5 to 3 tasks (auto-scaling: low CPU utilization).",
    type: "SCALING",
  },
  {
    id: "evt-010",
    timestamp: "2026-02-27T09:05:00Z",
    serviceName: "api-v2",
    clusterName: "prod-cluster",
    message: "service api-v2 has reached a steady state. Deployment ecs-svc/dep-003b completed.",
    type: "DEPLOYMENT",
  },
];
